### ISSUE TITLE
笔误，建议更改

### ISSUE THREAD

**Issue by leotengfei** [PanJiaChen/vue-element-admin-site#16]
https://github.com/PanJiaChen/vue-element-admin-site/blob/master/docs/zh/guide/essentials/deploy.md

这里的《强烈建议开启 gizp ，》

应为 《强烈建议开启gzip》

**Comment by PanJiaChen** [comment]
感谢提醒~ 
Fixed in https://github.com/PanJiaChen/vue-element-admin-site/commit/f972111504b74d2c182444760c6c3af29462518f
