### ISSUE TITLE
Hard to understand lines in cors.md

### ISSUE THREAD

**Issue by n05la3** [PanJiaChen/vue-element-admin-site#28]
What does this line in cors.md really want to say?
"But is usually trouble back-end development do not want to do this. That pure front-end is also has solutions."

**Comment by PanJiaChen** [comment]
> But there are always some back-end developers who think cors is too much trouble, they don't want to help the front end to solve cross-domain issues. That pure front-end is also has solutions.


My question, the document has been updated
