### ISSUE TITLE
The Spanish language is added but it does not take the translation

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [PanJiaChen/vue-element-admin-site#43]
## As you can see it takes the translation of the main nav

> /docs/.vuepress/config.js

![Captura de pantalla (9)](https://user-images.githubusercontent.com/20288327/56108343-713aa280-5f19-11e9-95f7-db081a4603ce.png)
![Captura de pantalla (8)](https://user-images.githubusercontent.com/20288327/56108342-713aa280-5f19-11e9-82b3-743b14797371.png)

## However it does not take language type in for the nav sumenu

> /docs/.vuepress/nav.js

![Captura de pantalla (6)](https://user-images.githubusercontent.com/20288327/56108340-70a20c00-5f19-11e9-9cae-e30c8e76c18d.png)
![Captura de pantalla (7)](https://user-images.githubusercontent.com/20288327/56108341-713aa280-5f19-11e9-9dee-70e238931e33.png)

### The type of language in the genNav function is sent as a parameter but it takes the type by default

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin-site/blob/99010338f277291ac3c944a429d6ed9cc0ac33c5/docs/.vuepress/utils.js#L5-L23

https://github.com/PanJiaChen/vue-element-admin-site/blob/99010338f277291ac3c944a429d6ed9cc0ac33c5/docs/.vuepress/config.js#L45-L47
