### ISSUE TITLE
Feature: Add initial translation of the Spanish language

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [PanJiaChen/vue-element-admin-site#45]
I currently have a branch with some corrections for English and the initial translation for the Spanish language, although a large part of the documentation still needs to be translated.

It can be very helpful and I intend to translate the existing language sequentially into Spanish to collaborate with your project.

https://github.com/EdwinBetanc0urt/vue-element-admin-site/tree/feature/add-spanish-lang

**Comment by PanJiaChen** [comment]
Amazing job 👍 

PR welcome.
