### ISSUE TITLE
文档问题 redirect: 'noredirect'

### ISSUE THREAD

**Issue by abel-wang-git** [PanJiaChen/vue-element-admin-site#55]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E9%85%8D%E7%BD%AE%E9%A1%B9

> //当设置 noredirect 的时候该路由在面包屑导航中不可被点击
redirect: 'noredirect'

应该为
redirect: 'noRedirect'
才有效

**Comment by PanJiaChen** [comment]
谢谢，已修改。
https://github.com/PanJiaChen/vue-element-admin-site/commit/c9339cf8e899f96f375ab4ce9df8ea82da03a996

**Comment by erhuodaosi** [comment]
@PanJiaChen 

亲测redirect: 'noRedirect'无效，
redirect: 'noredirect'才有效
